-- Insert sample visits data
INSERT INTO visits (
  patient_name,
  patient_surname,
  patient_phone,
  patient_email,
  patient_birth_date,
  patient_gender,
  visit_date,
  visit_type,
  chief_complaint,
  diagnosis,
  treatment,
  medications,
  notes,
  visit_cost
) VALUES 
(
  'Fatmir',
  'Berisha',
  '+383 44 111 222',
  'fatmir.berisha@email.com',
  '1985-03-15',
  'Mashkull',
  NOW() - INTERVAL '2 days',
  'Kontroll i rregullt',
  'Dhimbje koke dhe temperaturë',
  'Grip sezonal',
  'Pushim dhe hidratim',
  'Paracetamol 500mg, 3 herë në ditë',
  'Pacienti duhet të kthehet pas 1 jave nëse simptomat vazhdojnë',
  25.00
),
(
  'Valdete',
  'Gashi',
  '+383 44 333 444',
  'valdete.gashi@email.com',
  '1992-07-22',
  'Femër',
  NOW() - INTERVAL '1 day',
  'Vizitë urgjente',
  'Dhimbje barku dhe të vjella',
  'Gastroenterit akut',
  'Dieta dhe medikamente',
  'Omeprazol 20mg, 2 herë në ditë',
  'Pacienti u përmirësua pas trajtimit',
  35.00
),
(
  'Arben',
  'Hoxha',
  '+383 44 555 666',
  'arben.hoxha@email.com',
  '1978-11-08',
  'Mashkull',
  NOW() - INTERVAL '3 days',
  'Kontroll i rregullt',
  'Kontroll i tensionit të gjakut',
  'Hipertension i lehtë',
  'Ndryshime në dietë dhe ushtrime',
  'Lisinopril 10mg, 1 herë në ditë',
  'Kontrolli i radhës pas 1 muaji',
  30.00
),
(
  'Blerta',
  'Kelmendi',
  '+383 44 777 888',
  'blerta.kelmendi@email.com',
  '1995-05-12',
  'Femër',
  NOW() - INTERVAL '5 days',
  'Kontroll i rregullt',
  'Dhimbje fyti dhe kollë',
  'Faringit bakterial',
  'Antibiotikë dhe pushim',
  'Amoxicillin 500mg, 3 herë në ditë për 7 ditë',
  'Pacienti duhet të përfundojë kursin e antibiotikëve',
  40.00
),
(
  'Driton',
  'Mustafa',
  '+383 44 999 000',
  'driton.mustafa@email.com',
  '1988-12-03',
  'Mashkull',
  NOW() - INTERVAL '1 week',
  'Vizitë urgjente',
  'Lëndim në këmbë gjatë sportit',
  'Distorsion i kyçit të këmbës',
  'Pushim, akull dhe bandazhim',
  'Ibuprofen 400mg, 3 herë në ditë',
  'Pacienti duhet të shmangë aktivitetet sportive për 2 javë',
  45.00
);
